trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'damigah/celebrities'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'docker pull damigah/celebrities:latest'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
